[tox]
envlist = build
skipsdist = True

[testenv]
basepython = python3.11

# pip-sync: https://github.com/tox-dev/tox/issues/149
allowlist_externals =
    black
    isort
    mypy
    pip-sync

[testenv:build]
commands_pre =
    pip-sync --python-executable "{envpython}" src/requirements.txt
commands =
    black --check src cdk
    isort --check-only src cdk
    mypy --python-executable "{envpython}" --strict src

[testenv:format]
commands =
    black src cdk
    isort src cdk

[testenv:test]
commands_pre =
    pip install -r tests/requirements.txt
    pip install -e .
commands =
    coverage run --source src -m pytest --verbose tests
    coverage html
    coverage xml
    coverage report --show-missing

[testenv:test_integ]
commands_pre =
    pip-sync --python-executable "{envpython}" integ_tests/requirements.txt
commands =
    pytest integ_tests --verbose -rA --target_account_id "{env:PU_INTEG_TESTS_TARGET_ACCOUNT_ID}" \
            --profile "{env:PU_DEV_AWS_PROFILE}"

[testenv:test_integ_pipeline]
commands_pre =
    pip-sync --python-executable "{envpython}" integ_tests/requirements.txt
commands =
    pytest integ_tests --verbose -rA --target_account_id "{env:PU_INTEG_TESTS_TARGET_ACCOUNT_ID}" \
            --use_default_aws_credentials
passenv =
    AWS_CONTAINER_CREDENTIALS_RELATIVE_URI
    AWS_DEFAULT_REGION
